services:
  php-app:
    build:
      context: ./
      dockerfile: Dockerfile

    ports:
      - "90:80"

    volumes:
      - .:/var/www/html

    environment:
      PHP_TIMEZONE: America/Guatemala

    extra_hosts:
      - "host.docker.internal:host-gateway"

    depends_on:
      - database
      - phpmyadmin

    networks:
      - app-network

  database:
    image: mariadb:latest

    restart: always

    ports:
      - "3310:3306"

    environment:
      MYSQL_ROOT_PASSWORD: comercial
      MYSQL_DATABASE: comercial
      MYSQL_USER: comercial
      MYSQL_PASSWORD: comercial

    volumes:
      - mariadb_data:/var/lib/mysql

    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest

    restart: always

    ports:
      - "8087:80"

    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: comercial
      UPLOAD_LIMIT: 64M

    depends_on:
      - database

    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mariadb_data: